name: rtfd
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy>=1.15.0
  - scipy>=1.1.0
  - numba>=0.40.0
  - matplotlib
  - empymod
  - scooby
  - discretize
  - setuptools_scm
  - pip
  - pip:
    - sphinx<2.0
    - numpydoc
    - sphinx_rtd_theme
    - sphinx_gallery
    - sphinx_numfig
