# http://conda.pydata.org/docs/travis.html
language: python

matrix:
  include:
    - python: 3.6  # => 3.7
      env: PYTHON=3.7 PCKGS="mkl mkl-service numba" CHAN="defaults"
    - python: 3.6  # => 3.7 with conda-forge and IPython
      env: PYTHON=3.7 PCKGS="numba IPython" CHAN="conda-forge"

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --all
  # Useful for debugging any issues with conda
  - conda info -a

  # Install and activate environment, install packages
  - conda create -q -n test-environment -c $CHAN python=$PYTHON numpy scipy pytest pytest-cov $PCKGS
  - source activate test-environment
  - pip install coveralls pytest-flake8 discretize
  - python setup.py install


script: pytest --cov=emg3d --flake8

after_success: coveralls
